### ISSUE TITLE
Adding filter to Pipeline will reset the window title to "Untitled"

### ISSUE THREAD

**Issue by mmarineBlueQuartz** [BlueQuartzSoftware/SIMPLView#2]
Open DREAM.3D
Add a single filter
Save the pipeline to a file.
Note the Window Title will be the name of the Pipeline file.
Add another file. The window title now changes to "Untitled".

Moved from DREAM3D

**Comment by imikejackson** [comment]
Let's figure out how to run these files through clang-format on windows so that the files can conform to the formatting spec for DREAM3D and its supporting projects.
